#! /usr/local/conda2/bin/python
import time

def sysvar(filename, t='int'):
    try:
        with open(filename, 'r') as fd:
            val = fd.readline().rstrip()
        return int(val) if val.isdigit() else val
    except:
        return '---'

def powercap_info(filename):
    print '{}/'.format(filename)
    print '  name: {}'.format(
        sysvar(filename+'/name'))
    print '    constraint_0:'
    print '      name: {}'.format(
        sysvar(filename+'/constraint_0_name'))
    print '      max_power_uw: {}'.format(
        sysvar(filename+'/constraint_0_max_power_uw'))
    print '      power_limit_uw: {}'.format(
        sysvar(filename+'/constraint_0_power_limit_uw'))
    print '      time_window_us: {}'.format(
        sysvar(filename+'/constraint_1_time_window_us'))
    print '    constraint_1:'
    print '      name: {}'.format(
        sysvar(filename+'/constraint_1_name'))
    print '      max_power_uw: {}'.format(
        sysvar(filename+'/constraint_1_max_power_uw'))
    print '      power_limit_uw: {}'.format(
        sysvar(filename+'/constraint_1_power_limit_uw'))
    print '      time_window_us: {}'.format(
        sysvar(filename+'/constraint_1_time_window_us'))

powercap_info('/sys/class/powercap/intel-rapl:0')
#powercap_info('/sys/class/powercap/intel-rapl:0:0')
#powercap_info('/sys/class/powercap/intel-rapl:0:1')
#powercap_info('/sys/class/powercap/intel-rapl:0:2')
powercap_info('/sys/class/powercap/intel-rapl:1')
