#! /usr/local/conda2/bin/python
import time

def read(filename, t='int'):
    with open(filename, 'r') as fd:
        val = fd.readline().rstrip()
    return int(val) if val.isdigit() else val

def print_power(filename):    
    try:
        print '<{}>'.format(filename)
        e0 = read('{}/energy_uj'.format(filename))
        t0 = time.time()
        time.sleep(1)
        e1 = read('{}/energy_uj'.format(filename))
        t1 = time.time()
        
        print "  Name: {}".format(read('{}/name'.format(filename)))
        print "  Power: {:.3f}W".format((e1-e0)/(t1-t0)/1e6)
    except:
        print "   ???"

        
print_power('/sys/class/powercap/intel-rapl:0')
print_power('/sys/class/powercap/intel-rapl:0:0')
print_power('/sys/class/powercap/intel-rapl:0:1')
print_power('/sys/class/powercap/intel-rapl:0:2')
print_power('/sys/class/powercap/intel-rapl:1')